theme: minima
title: About Me
author: Amanda Aird
email: amanda-aird@uiowa.edu
description: > # this means to ignore newlines until "baseurl:"
  Here's some info about me!


show_excerpts: true # set to false to remove excerpts on the homepage
